### ISSUE TITLE
Test broken on dev branch

### ISSUE THREAD

**Issue by rcpeters** [andreareginato/simple-oauth2#37]
When testing against master `make test` passes. However if I checkout the `dev` branch I get a `Cannot read property 'message' of undefined` error. Console log below:

        MacBook-Pro:simple-oauth2 rcpeters$ git checkout master
        Switched to branch 'master'
        Your branch is up-to-date with 'origin/master'.
        MacBook-Pro:simple-oauth2 rcpeters$ make test
        child_process: customFds option is deprecated, use stdio instead.
        
          ․․․․․․․․․․․․․․․․․
        
          17 tests complete (39 ms)
        
        MacBook-Pro:simple-oauth2 rcpeters$ git checkout master 
        Already on 'master'
        Your branch is up-to-date with 'origin/master'.
        MacBook-Pro:simple-oauth2 rcpeters$ make test
        child_process: customFds option is deprecated, use stdio instead.
        
          ․․․․․․․․․․․․․․․․․
        
          17 tests complete (38 ms)
        
        MacBook-Pro:simple-oauth2 rcpeters$ git checkout andreareginato/dev
        Note: checking out 'andreareginato/dev'.
        
        You are in 'detached HEAD' state. You can look around, make experimental
        changes and commit them, and you can discard any commits you make in this
        state without impacting any branches by performing another checkout.
        
        If you want to create a new branch to retain commits you create, you may
        do so (now or later) by using -b with the checkout command again. Example:
        
          git checkout -b new_branch_name
        
        HEAD is now at 4db50b7... Merge branch 'master' of github.com:andreareginato/simple-oauth2
        MacBook-Pro:simple-oauth2 rcpeters$ make test
        child_process: customFds option is deprecated, use stdio instead.
        
          ․․․․․․․․․․․․․․․․
        
          ✖ 2 of 16 tests failed:
        
          1) Simple OAuth2 Error with status code 401 returns an access token:
             TypeError: Cannot read property 'message' of undefined
              at Context.<anonymous> (/Users/rcpeters/git/simple-oauth2/test/errors.js:30:17)
              at Test.Runnable.run (/Users/rcpeters/git/simple-oauth2/node_modules/mocha/lib/runnable.js:213:32)
              at Runner.runTest (/Users/rcpeters/git/simple-oauth2/node_modules/mocha/lib/runner.js:344:10)
              at /Users/rcpeters/git/simple-oauth2/node_modules/mocha/lib/runner.js:390:12
              at next (/Users/rcpeters/git/simple-oauth2/node_modules/mocha/lib/runner.js:270:14)
              at /Users/rcpeters/git/simple-oauth2/node_modules/mocha/lib/runner.js:279:7
              at next (/Users/rcpeters/git/simple-oauth2/node_modules/mocha/lib/runner.js:227:23)
              at /Users/rcpeters/git/simple-oauth2/node_modules/mocha/lib/runner.js:242:7
              at done (/Users/rcpeters/git/simple-oauth2/node_modules/mocha/lib/runnable.js:187:5)
              at /Users/rcpeters/git/simple-oauth2/node_modules/mocha/lib/runnable.js:199:9
              at /Users/rcpeters/git/simple-oauth2/test/errors.js:21:28
              at data (/Users/rcpeters/git/simple-oauth2/lib/core.js:67:44)
              at Request._callback (/Users/rcpeters/git/simple-oauth2/lib/core.js:23:7)
              at Request.self.callback (/Users/rcpeters/git/simple-oauth2/node_modules/request/main.js:122:22)
              at Request.emit (events.js:110:17)
              at Request.<anonymous> (/Users/rcpeters/git/simple-oauth2/node_modules/request/main.js:661:16)
              at Request.emit (events.js:129:20)
              at OutgoingMessage.<anonymous> (/Users/rcpeters/git/simple-oauth2/node_modules/request/main.js:623:14)
              at OutgoingMessage.emit (events.js:104:17)
              at /Users/rcpeters/git/simple-oauth2/node_modules/nock/lib/request_overrider.js:208:18
              at /Users/rcpeters/git/simple-oauth2/node_modules/nock/lib/request_overrider.js:215:21
              at process._tickCallback (node.js:355:11)
        
          2) Simple OAuth2 Error with status code 500 returns an access token:
             TypeError: Cannot read property 'message' of undefined
              at Context.<anonymous> (/Users/rcpeters/git/simple-oauth2/test/errors.js:54:17)
              at Test.Runnable.run (/Users/rcpeters/git/simple-oauth2/node_modules/mocha/lib/runnable.js:213:32)
              at Runner.runTest (/Users/rcpeters/git/simple-oauth2/node_modules/mocha/lib/runner.js:344:10)
              at /Users/rcpeters/git/simple-oauth2/node_modules/mocha/lib/runner.js:390:12
              at next (/Users/rcpeters/git/simple-oauth2/node_modules/mocha/lib/runner.js:270:14)
              at /Users/rcpeters/git/simple-oauth2/node_modules/mocha/lib/runner.js:279:7
              at next (/Users/rcpeters/git/simple-oauth2/node_modules/mocha/lib/runner.js:227:23)
              at /Users/rcpeters/git/simple-oauth2/node_modules/mocha/lib/runner.js:242:7
              at done (/Users/rcpeters/git/simple-oauth2/node_modules/mocha/lib/runnable.js:187:5)
              at /Users/rcpeters/git/simple-oauth2/node_modules/mocha/lib/runnable.js:199:9
              at /Users/rcpeters/git/simple-oauth2/test/errors.js:45:28
              at data (/Users/rcpeters/git/simple-oauth2/lib/core.js:67:44)
              at Request._callback (/Users/rcpeters/git/simple-oauth2/lib/core.js:23:7)
              at Request.self.callback (/Users/rcpeters/git/simple-oauth2/node_modules/request/main.js:122:22)
              at Request.emit (events.js:110:17)
              at Request.<anonymous> (/Users/rcpeters/git/simple-oauth2/node_modules/request/main.js:661:16)
              at Request.emit (events.js:129:20)
              at OutgoingMessage.<anonymous> (/Users/rcpeters/git/simple-oauth2/node_modules/request/main.js:623:14)
              at OutgoingMessage.emit (events.js:104:17)
              at /Users/rcpeters/git/simple-oauth2/node_modules/nock/lib/request_overrider.js:208:18
              at /Users/rcpeters/git/simple-oauth2/node_modules/nock/lib/request_overrider.js:215:21
              at process._tickCallback (node.js:355:11)
        
        
        make: *** [test] Error 2

**Comment by jonathansamines** [comment]
Hi, the dev branch seems to be outdated in respect to the master branch. @andreareginato should be update this branch to the master state and start to accept pull requests only to this branch and then integrate those changes to master? I´ll think that this will be less error-prone and will allow us to mantain master accordying to the last release made to npm.

**Comment by andreareginato** [comment]
From a theoretical point of view yes. I use the dev branch for development and then move to master. Anyway, from experience people uses directly the master branch on 90% of cases. 

I would love to understand if there are some "best practices" to make this flow work and, as you say, less error prone.

**Comment by jonathansamines** [comment]
Hi @andreareginato id don´t know if there are some **best practices**, but from my point of view "master" should always be deployable (latest npm published version), so people don´t get confused with the docs (which may nor represent which is published on npm in the way is currently working). Also we should be using semver to publish new versions and tag every version released to npm ( so it is possible to read the documentation related to a specific npm module version). 

Those aren´t "best practices" at all, but will make easier to other people to get involved on this project, or even simply using it over the time.

**Comment by andreareginato** [comment]
@jonathansamines I agree. Lets make it clear in the doc.

**Comment by jonathansamines** [comment]
Yes i´ll work on this this week or the next, so we can have a better contributions model. :facepunch:

**Comment by jonathansamines** [comment]
The development branch was updated and now the test passes on this branch. Also note that the branch name was changed to "develop". Some details on #50 and #51.
